version: '2'
services:
  zookeeper:
    image: wurstmeister/zookeeper
    ports:
      - "2181:2181"

  kafka:
    image: wurstmeister/kafka
    # build: .
    ports:
      - "9092:9092"
    environment:
      KAFKA_ADVERTISED_HOST_NAME: 10.90.17.163
      KAFKA_CREATE_TOPICS: "test:1:1,spp:1:1,A:1:1,B:1:1,C:1:1,D:1:1,E:1:1,G:1:1,source:1:1,intermediate:1:1,destination:1:1"
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      DELETE_TOPIC_ENABLE: "true"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - ./kafka_logs:/kafka

#  kafka-manager:
#    image: sheepkiller/kafka-manager
#    ports:
#      - "80:9000"
#    environment:
#      ZK_HOSTS: "zookeeper:2181"
#      APPLICATION_SECRET: "pass"
#
#  zookeeper-ui:
#    image: tobilg/zookeeper-webui
#    ports:
#      - "8080:8080"
#    environment:
#      ZK_DEFAULT_NODE: zookeeper:2181
